name: gaigs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - setuptools
  - ninja
  - pytorch=2.1
  - torchvision=0.16
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - pandas
  - scikit-image
  - pyyaml
  - plyfile
  - tqdm
  - einops
  - imageio
  - pillow
  - pip:
    - opencv-python
    - clifford
    - opt-einsum
    - mlflow
    - xformers
    - performer-pytorch
    - ./submodules/diff-gaussian-rasterization
    - ./submodules/simple-knn
    - ./submodules/fused-ssim
